openapi: 3.1.0
info:
  title: OneCell ← LIS Integration API
  version: "1.12.0"
  license:
    name: Commercial
    url: https://onecell.ai/#api-license
  description: |-
    Данный домумент описывает конечные точки (endpoints), 
    которые реализует **ПАКС OneCell** со своей стороны для интеграции с **ЛИС**.

    ЛИС будет делать запросы на данные конечные точки для передачи информации из **ЛИС** в **ПАКС**.

servers:
  - url: https://integration.onecell.acme.corp
paths:
  /lis/v1/case:
    $ref: paths/lis_v1_case.yaml
  /lis/v1/case/{caseNumber}/medical-report:
    $ref: paths/lis_v1_case_{caseNumber}_medical-report.yaml
  /lis/v1/dictionary/stain:
    $ref: paths/lis_v1_dictionary_stain.yaml
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
