name: Publish OpenAPI

on:
  push:
    branches:
      - **

jobs:
  build:
    runs-on: ubuntu-latest    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write

    env:
      BRANCH_PATH: branch/${{ github.ref_name }}
      DOMAIN: onecellai.github.io

    steps:
      # Comment on branch
      - name: Comment on branch
        uses: hasura/comment-progress@v2.3.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "Starting deployment of preview ⏳..."

      # Checkout the current branch
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build-docs script
      - name: Build Redocly docs
        run: npm run build

      # Upload docs to GitHub Pages
      - name: Deploy to GitHub Pages (main branch)
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Set base URL for preview if PR
        if: github.ref != 'refs/heads/main'
        run: echo "BASE_URL=https://${{ env.DOMAIN }}/${{ github.event.repository.name }}/${{ env.PR_PATH }}/" >> $GITHUB_ENV

      - name: Deploy to PR preview
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref != 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ${{ env.PR_PATH }}

      - name: Update comment
        uses: hasura/comment-progress@v2.2.0
        if: github.ref != 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.number }}
          id: deploy-preview
          message: "A preview of ${{ github.event.after }} is uploaded and can be seen here:\n\n ✨ ${{ env.BASE_URL }} ✨\n\nChanges may take a few minutes to propagate."
